### PR TITLE
Version 3

### PR DESCRIPTION
**Pull request by nhooyr**
# Introduction
The present API has issues with understanding the code flow and state.
E.g. to get state out of Run, you pass in a closure that mutates the state
you want to use afterwords. The way errors are passed around is also janky.

Furthermore, the Log function and post conditions are janky and not much
better than a chain of if statements or a switch statement.

This new API will make the code flow much cleaner because it does not
use a Run function and instead allows the caller to integrate retry into
their own loop. This will let them set pre-conditions and post-conditions
natively with if statements and is overall a much more idiomatic approach.

# Example

Before:
```go
start := time.Now()

err := retry.New(time.Second).
	Jitter(0.5).
	Timeout(time.Second * 10).
	Attempts(5).
	Run(func() error {
		return errors.New("not enough time has elapsed")
	})
fmt.Printf("err: %v, took %v\n", err, time.Since(start))
```

After:
```go
start := time.Now()

rm := retry.New(time.Second).
	Jitter(0.5).
	Timeout(time.Second * 10).
	MaxAttempts(5)
for {
	err := rm.Next()
	if err != nil {
		fmt.Printf("err: %v, took %v\n", err, time.Since(start))
		break
	}
	// something...
}
```

## Alternatives

I considered an approach similar to `bufio.Scanner` where we would have a `Next` method on the retry manager that returned bool and then a `Err` method to grab the error. The usage would look like this:

```go
start := time.Now()

rm := retry.New(time.Second).
	Jitter(0.5).
	Timeout(time.Second * 10).
	MaxAttempts(5)
for rm.Next() {
	// something...
}
if rm.Err() != nil {
	fmt.Printf("err: %v, took %v\n", rm.Err(), time.Since(start))
}
```

I like that as well but opted for having `Next` return an error because I think its simpler and makes retry less "special" if they have other pre conditions for example because they would all be structured the same. Furthermore, the code flow is more clear and easier to understand.

## TODOs

This is blocked on #20 and vgo.

Furthermore, need to update the tests and docs.

I've opened this for discussion.

### CODE REVIEW

**Comment by ammario** [comment]
I think the `Next() bool` leads to cleaner code.. We're looking at a minimum of 2 error handling points in the `Next() error` model.

**Comment by nhooyr** [comment]
Why would there be a minimum of 2 error handling points in the `Next() error` model?

**Comment by nhooyr** [comment]
^ Github pooped.

**Comment by ammario** [comment]
Because you're checking the error from Next and then you're checking the error from the underlying operation.

**Comment by nhooyr** [comment]
Not sure what you mean. Could you give an example?

**Comment by ammario** [comment]
It still happens, it's just outside the loop, so it's clear that it's not related to the operation being retried.

**Comment by nhooyr** [comment]
Its is related to the operation being retried. Making retry.Err() special and moving it out of the loop is what I think makes it unclear because a user could have their own pre/post conditions, why should our retry package be special?

**Comment by ammario** [comment]
```go
start := time.Now()

rm := retry.New(time.Second).
	Jitter(0.5).
	Timeout(time.Second * 10).
	MaxAttempts(5)
for rm.Next() {
	// something...
}
if rm.Failed() {
	fmt.Printf("%v\n", rm.Wrap(err))
}
```
?

**Comment by foresthoffman** [comment]
```go
...
fmt.Printf("%v\n", rm.Wrap(err))
...
```
Where is `err` being defined in this flow? Are we still supplying an `Err()` method?

**Comment by ammario** [comment]
I suppose it would be whatever error was generated by the loop.

**Comment by foresthoffman** [comment]
Oh, I see. That looks good to me, then. 👍

**Comment by nhooyr** [comment]
I'm confused. What does `rm.Wrap()` do? Is this to solve #23?

**Comment by nhooyr** [comment]
I also think we should remove the chain API. I don't feel like it semantically makes sense. Not returning the retry would be cleaner for each option to be on its own line.

**Comment by nhooyr** [comment]
I also think we should remove the Context function. Callers should check themselves because it makes retry kinda weird in that for the first iteration it doesn't sleep. Rather, the retry should be at the end of the loop and the caller check the context at the start if they want.

**Comment by nhooyr** [comment]
(will also tag v1/v2 after this)

**Pull request merged**
